### ISSUE TITLE
Create a Webpage for "Tuples in Python"

### ISSUE THREAD

**Issue by akshwin** [X-Evolve/Python_Hunt#10]
1) Explain what is a tuple in Python
2) Different functions in Tuple
3) Add code snippers for all the examples

**Comment by mismathh** [comment]
Hi @akshwin, I would like to work on this issue. Could you please assign this issue to me? Thanks!

**Comment by akshwin** [comment]
Hello @mismathh , I am assigning this issue to you. Please refer to CONTRIBUTING.md file once, and start contributing.
Thank you!
