### ISSUE TITLE
Create a Web Page for "Python Keywords"

### ISSUE THREAD

**Issue by ravin-d-27** [X-Evolve/Python_Hunt#2]
It should display All Keywords in tabular form along with One line information about it.
Also, add some code snippets for some important keywords according to your preference

**Comment by KarthikAkshaj** [comment]
hello @ravin-d-27 
i am interested in doing this issue
so kindly assign me this 
Thank You : )

**Comment by ravin-d-27** [comment]
Hi @KarthikAkshaj ! Thats great. I am assigning this issue to you. Please keep us updated here!
Thank you!

**Comment by ravin-d-27** [comment]
Hello @KarthikAkshaj, what is the status of your contribution?

**Comment by KarthikAkshaj** [comment]
Yeah i worked on the issue and i will be pushing request soon.... Sorry for the late

**Comment by ravin-d-27** [comment]
Done!
