### ISSUE TITLE
About Python page has inconsistent navbar, also when you press login or sign up there is no animation. 

### ISSUE THREAD

**Issue by Miran-Firdausi** [X-Evolve/Python_Hunt#44]
Also in keywords page, code snippets is not responsive. I want to work on this project. Let me know if you have any other work for me.

**Comment by Sriram-Ramakrishnan** [comment]
Hey @Miran-Firdausi ! I appreciate your initiative, hence I am assigning this issue to you. Make the pull request at the earliest possible.
