### ISSUE TITLE
Design python_data_types.html Page

### ISSUE THREAD

**Issue by ravin-d-27** [X-Evolve/Python_Hunt#54]
Refer to other HTML Pages and make the `python_data_types.html` look uniform.
Add **Navbar** to it as well, with required stylings.

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this, please assign

**Comment by ravin-d-27** [comment]
Hey @IrfanSalim, I am assigning this issue to you. Please make your PR within 3 days.
