### ISSUE TITLE
Create a Webpage for "Python Data Types"

### ISSUE THREAD

**Issue by akshwin** [X-Evolve/Python_Hunt#6]
1)Explain what is a data type
2)Different data types 
3)Include code snippets for all type of data types

**Comment by Pulkitxm** [comment]
Can I Get assigned ?

**Comment by akshwin** [comment]
Hi , I am assigning you the issue .

**Comment by ravin-d-27** [comment]
@Pulkitxm , could you please let us know the progress?

**Comment by Pulkitxm** [comment]
Hey Just added the webpage in this [PR](https://github.com/X-Evolve/Python_Hunt/pull/12)
I was just busy with other work SOrry for delay
