### ISSUE TITLE
Create a Webpage for "File Handling"

### ISSUE THREAD

**Issue by ravin-d-27** [X-Evolve/Python_Hunt#64]
Refer to `README.md` file and cover the below topics
1. **Opening and Closing Files**:
   - `open()`
   - `close()`

2. **Reading Files**:
   - `read()`
   - `readline()`
   - `readlines()`

3. **Writing to Files**:
   - `write()`
   - `writelines()`

4. **Appending to Files**:
   - `append()`

5. **File Modes**:
   - `r` (Read)
   - `w` (Write)
   - `a` (Append)
   - `b` (Binary)
   - `x` (Create)

6. **Working with Binary Files**:
   - `rb`
   - `wb`
   - `ab`

7. **File Attributes**:
   - `name`
   - `mode`

8. **Navigating within Files**:
   - `seek()`
   - `tell()`

9. **Error Handling with Files**:
   - `try` and `except` for file-related errors

10. **Using `with` Statement**:
    - Automatic file closing

11. **Working with Text and Binary Files**:
    - `open()` with `t` and `b` modes

12. **Working with CSV Files**:
    - Using the `csv` module

13. **Working with JSON Files**:
    - Using the `json` module

14. **Working with XML Files**:
    - Using libraries like `xml.etree.ElementTree`

15. **Working with Excel Files**:
    - Using libraries like `pandas`, `openpyxl`, `xlrd`, `xlwt`, etc.

16. **Managing Directories**:
    - `os` module for directory operations

17. **File Metadata**:
    - `os.path` for file-related information

18. **File Handling Best Practices**:
    - Properly closing files
    - Using `with` statement for automatic cleanup

**Comment by Umesh9-prog** [comment]
Hi @ravin-d-27 can u assign this issue to me

**Comment by ravin-d-27** [comment]
Hi @Umesh9-prog , I am assigning this issue to you, please make a PR within a week.

**Comment by Umesh9-prog** [comment]
Sure @ravin-d-27

**Comment by Umesh9-prog** [comment]
hi @ravin-d-27, created PR do checkIt out!

**Comment by ravin-d-27** [comment]
That's great! Closing this issue as it is completed!
