### ISSUE TITLE
Create a Web Page for "Loops and Iterative Statements"

### ISSUE THREAD

**Issue by ravin-d-27** [X-Evolve/Python_Hunt#69]
Create a Webpage which explains about `For` loop and `While` loop.
It should have sample code snippets which explains the concepts pretty well.
HTML page should be uniform, please have a look at other pages and create it.

Refer to `README.md` and make the PR.

**Comment by Umesh9-prog** [comment]
Hi @ravin-d-27 can you please assign these issues to me

**Comment by ravin-d-27** [comment]
Hi @Umesh9-prog , welcome back. I am assigning this issue to you. please make a PR within 3 days of time.

**Comment by Umesh9-prog** [comment]
@ravin-d-27 thanks for assigning the issue ! Will create PR soon

**Comment by Umesh9-prog** [comment]
hi @ravin-d-27 i have created pull request do check it out

**Comment by ravin-d-27** [comment]
Closing this issue as it is completed .
