### ISSUE TITLE
Create a web page for "Python Lists"

### ISSUE THREAD

**Issue by akshwin** [X-Evolve/Python_Hunt#7]
1) Explain what is a list 
2) How to declare a list in python 
3)Some important list functions
4)Code snippets to explain all

**Comment by ShatilKhan** [comment]
Please assign this issue to me. I have experience in Python & have done docs contributions before

**Comment by ravin-d-27** [comment]
Hello @ShatilKhan, I am assigning this issue to you. Please refer to CONTRIBUTING.md file once, and start contributing.
Thank you!

**Comment by ravin-d-27** [comment]
Hello @ShatilKhan, what is the status of your contribution?

**Comment by ShatilKhan** [comment]
I'm on it @ravin-d-27 
Will make my PR soon

**Comment by ravin-d-27** [comment]
That's Great @ShatilKhan !

**Comment by dheekshithbg** [comment]
Please re-assign this issue to me.

**Comment by ravin-d-27** [comment]
Hi @dheekshithbg, I am assigning this issue to you!

**Comment by ravin-d-27** [comment]
This issue is resolved
