### ISSUE TITLE
Misleading description on the signup page

### ISSUE THREAD

**Issue by NXKED** [X-Evolve/Python_Hunt#78]
Issue: 
Both the signup and login page show "Don't have an account?". 

Changing to "Already registered?" or something else as wanted.

![image](https://github.com/X-Evolve/Python_Hunt/assets/107938013/23143bf9-00e1-4d31-9bcb-685c2714fdaa)

**Comment by ravin-d-27** [comment]
Hi @NXKED ! Thanks for highlighting the issue! Will fix it asap!
