### ISSUE TITLE
Create a web page for Polymorphism in Python 

### ISSUE THREAD

**Issue by akshwin** [X-Evolve/Python_Hunt#91]
Create a web page on Polymorphism explaining the basic concepts with example.
It should cover all the concepts with example

**Comment by BuilderPrid** [comment]
Can you please assign this to me?

**Comment by akshwin** [comment]
Assigning this issue to you @BuilderPrid . Refer to the documentation before contributing.
Thank You .

**Comment by BuilderPrid** [comment]
@akshwin I have made the appropriate changes to the code. Please review and let me know if any changes are desired.
