### ISSUE TITLE
Copyright dynamic year and footer enhancement

### ISSUE THREAD

**Issue by VishwasSaini25** [X-Evolve/Python_Hunt#96]
The copyright year is not dynamic as its 2024 and its showing 2023. Also the footer is in 2 lines, its better to enhance it. and make it inline.

**Comment by ravin-d-27** [comment]
Hi @VishwasSaini25 ! Thank you for highlighting the issue. Are you willing to contribute to this?

**Comment by VishwasSaini25** [comment]
yes, please assign it to me
